version: "3"
services: 
  db:
    image: postgres:latest
    ports: 
      - "5432:5432"
    volumes:
      - ./db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: docker
      POSTGRES_USER: postgres
      POSTGRES_DB: inventorydb
    networks:
      - app-network
  
  frontend:
    build: ./frontend
    ports: 
      - "3000:3000"
    volumes:
      - ./frontend:/frontend
    depends_on:
      - server
    networks:
      - app-network

  server:
    build: ./backend
    ports: 
      - "7999:7999"
    volumes:
      - ./backend:/backend
    depends_on:
      - db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge